name: github-workload-identity-federation-example

on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "ran-sandbox-1d2d"
          service_account: "github-ci@ran-sandbox-1d2d.iam.gserviceaccount.com"
          workload_identity_provider: "projects/419723385417/locations/global/workloadIdentityPools/github-pool/providers/github-provider"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0" # Warning! Workload Identity Federation requires version 363.0.0 or newer.

      - name: "gcloud usage"
        run: |-
          gcloud info
          gcloud auth list --filter=status:ACTIVE --format="value(account)"

# TODO next, deploy a cloud function https://github.com/google-github-actions/deploy-cloud-functions
